### PR TITLE
Add quote to ceiling

### PR DESCRIPTION
**Pull request by rmasianjr**
This PR addresses Issue #14 

- Add a random quote from [Forismatic API](https://forismatic.com/en/api/) to ceiling/top of dance space.
- fetching of quote will happen on load.
- if error occurs, show a button that can be click to fetch again a quote.

header-quote

### CODE REVIEW

**Comment by SmokinClove** [comment]
Thank you for the contribution :)

**Comment by SmokinClove** [comment]
@rmasianjr sorry could you help to resolve conflict with the remote master branch?

**Comment by rmasianjr** [comment]
@SmokinClove done sir.. :relieved: , i hope i didn't messed up  :sweat_smile:
still a beginner :)

**Comment by SmokinClove** [comment]
Thank you for the work :D

**Pull request merged**
