### PR TITLE
refactor positions and many more to hooks

### PR DESCRIPTION
**Pull request by tanhauhau**
sorry i feel like i've changed too much 🙈 

i've made the main function easy to my eyes (blame my own taste) 👀

### CODE REVIEW

**Comment by tanhauhau** [comment]
and i feel like i've created a subtle bug in your moonwalker somehow 🙊

**Comment by SmokinClove** [comment]
Ehh? D: wait haha i gotta look harder

**Comment by SmokinClove** [comment]
Oh did you mean the premature shift when changing the dance modes?

**Comment by tanhauhau** [comment]
yea....

**Comment by SmokinClove** [comment]
Got it. No need to make it blocking; please go ahead if you have a new dance move in mind XD i will take a look at the bug later

**Pull request merged**
