### PR TITLE
fix premature moves when switching dance moves

### LINKED ISSUE #5: Premature shift after changing mode
The first dance move is triggered while the dancer is stationary.

### PR DESCRIPTION
**Pull request by tanhauhau**
Fix #5

### CODE REVIEW

**Comment by SmokinClove** [comment]
Could you briefly explain why without capturing the latest ref the body will move even when the state is Stopping? 🙏

**Comment by SmokinClove** [comment]
i got a feeling the dance move and the step delay is off sync now 🤔

**Comment by tanhauhau** [comment]
> Could you briefly explain why without capturing the latest ref the body will move even when the state is Stopping?

actually the correct question is is caputring the latest ref the right way to fix? 🤷‍♂ 

well. i used the useEffect to move the dancer when `index` and `danceMove` changed. 
```
  useEffect(() => moveDancePosition(index), [index, moveDancePosition]);
```

`danceMove` change will cause the effect to fire because, `danceMove` change will cause `moveDancePosition` function change, which causes the effect to fire.

---

on noticing the off-sync, i think i shouldn't use `useEffect`, because
- `index` change -> 
- rerender with the latest `rightPos` and `animation` -> 
- finish render -> 
- fire side effects -> 
- moves the body parts

so i think there's a time gap between render -> fire side effects. 
let me try and fix this.

**Comment by SmokinClove** [comment]
Hmm not sure if this helps but i realised a potential instability with the current animation design: there is delay (the gap between steps) and the animationDuration (the duration of a single movement). Currently the delay can be changed with the input while the animationDuration is fixed.

**Comment by tanhauhau** [comment]
> Currently the delay can be changed with the input while the animationDuration is fixed.

the dancer stops when i change the delay right?

**Pull request merged**
